"""
Seed the database with demo accounts, hospital/department structure, doctors,
beds, and the synthetic patients/visits/appointments/events generated by
scripts/generate_dataset.py.

ALL DATA CREATED HERE IS SYNTHETIC / DEMO DATA — never real patient data.

Usage:
    python -m scripts.seed_database
"""
import os
import random
import sys
from datetime import datetime

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database.session import SessionLocal, Base, engine
from app.core.security import hash_password
from app.models.models import (
    User, RoleEnum, Hospital, Department, Doctor, Staff, Bed, BedStatusEnum,
    Patient, Visit, VisitTypeEnum, Appointment, AppointmentStatusEnum, HospitalEvent, SeverityEnum,
)

DEPARTMENTS = [
    {"name": "Emergency", "capacity": 100, "num_doctors": 12, "num_staff": 25, "num_beds": 30, "avg_handling_capacity": 60},
    {"name": "OPD - General Medicine", "capacity": 150, "num_doctors": 15, "num_staff": 20, "num_beds": 10, "avg_handling_capacity": 120},
    {"name": "Cardiology", "capacity": 60, "num_doctors": 8, "num_staff": 12, "num_beds": 20, "avg_handling_capacity": 40},
    {"name": "Orthopedics", "capacity": 50, "num_doctors": 6, "num_staff": 10, "num_beds": 15, "avg_handling_capacity": 30},
    {"name": "Pediatrics", "capacity": 70, "num_doctors": 7, "num_staff": 14, "num_beds": 18, "avg_handling_capacity": 45},
    {"name": "Radiology", "capacity": 40, "num_doctors": 5, "num_staff": 8, "num_beds": 5, "avg_handling_capacity": 25},
]

DEMO_USERS = [
    {"full_name": "Admin User", "email": "admin@hospital-ops.demo", "password": "Admin@123", "role": RoleEnum.ADMIN},
    {"full_name": "Hospital Manager", "email": "manager@hospital-ops.demo", "password": "Manager@123", "role": RoleEnum.HOSPITAL_MANAGER},
    {"full_name": "Department Manager", "email": "deptmanager@hospital-ops.demo", "password": "DeptMgr@123", "role": RoleEnum.DEPARTMENT_MANAGER},
    {"full_name": "Staff Member", "email": "staff@hospital-ops.demo", "password": "Staff@123", "role": RoleEnum.STAFF},
]

RAW_DIR = "ml/data/raw"


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(Hospital).first():
            print("Database already seeded. Skipping. (Delete hospital_ops.db to reseed.)")
            return

        hospital = Hospital(name="City General Hospital (Demo)", address="123 Health Ave", total_capacity=470)
        db.add(hospital)
        db.commit()
        db.refresh(hospital)

        dept_objs = {}
        for d in DEPARTMENTS:
            dept = Department(hospital_id=hospital.id, **d, operating_hours="00:00-23:59")
            db.add(dept)
            db.commit()
            db.refresh(dept)
            dept_objs[d["name"]] = dept

            for i in range(d["num_doctors"]):
                db.add(Doctor(department_id=dept.id, full_name=f"Dr. {dept.name.split()[0]} {i+1}",
                               specialization=dept.name))
            for i in range(d["num_staff"]):
                db.add(Staff(department_id=dept.id, full_name=f"Staff {dept.name.split()[0]} {i+1}",
                              role_title="Nurse", shift="Day"))
            for i in range(d["num_beds"]):
                status = random.choices(
                    [BedStatusEnum.AVAILABLE, BedStatusEnum.OCCUPIED, BedStatusEnum.RESERVED,
                     BedStatusEnum.CLEANING, BedStatusEnum.MAINTENANCE],
                    weights=[0.35, 0.5, 0.08, 0.05, 0.02]
                )[0]
                db.add(Bed(department_id=dept.id, ward=f"{dept.name} Ward", status=status))
            db.commit()

        # demo user accounts
        for u in DEMO_USERS:
            dept = list(dept_objs.values())[0] if u["role"] == RoleEnum.DEPARTMENT_MANAGER else None
            user = User(full_name=u["full_name"], email=u["email"], hashed_password=hash_password(u["password"]),
                        role=u["role"], department_id=dept.id if dept else None, is_demo=True)
            db.add(user)
        db.commit()
        print("Demo accounts created:")
        for u in DEMO_USERS:
            print(f"   {u['role'].value:22s} -> {u['email']} / {u['password']}")

        # Load synthetic operational data if available
        if os.path.exists(os.path.join(RAW_DIR, "visits.csv")):
            print("\nLoading synthetic visits/appointments/events into database...")

            visits_df = pd.read_csv(os.path.join(RAW_DIR, "visits.csv"))
            patient_cache = {}
            batch = 0
            for _, row in visits_df.iterrows():
                key = (row["patient_age_group"], row["patient_gender"], row["patient_region"])
                if key not in patient_cache:
                    p = Patient(age_group=row["patient_age_group"], gender=row["patient_gender"],
                                region=row["patient_region"])
                    db.add(p)
                    db.flush()
                    patient_cache[key] = p.id
                dept = dept_objs.get(row["department"])
                if not dept:
                    continue
                db.add(Visit(
                    patient_id=patient_cache[key], department_id=dept.id, visit_type=row["visit_type"],
                    arrival_time=pd.to_datetime(row["arrival_time"]), departure_time=pd.to_datetime(row["departure_time"]),
                    waiting_time_minutes=row["waiting_time_minutes"], visit_status=row["visit_status"],
                ))
                batch += 1
                if batch % 2000 == 0:
                    db.commit()
            db.commit()
            print(f"   Inserted {len(visits_df)} visits (deduplicated into {len(patient_cache)} synthetic patient profiles)")

            appts_df = pd.read_csv(os.path.join(RAW_DIR, "appointments.csv"))
            batch = 0
            for _, row in appts_df.iterrows():
                dept = dept_objs.get(row["department"])
                if not dept:
                    continue
                pid = random.choice(list(patient_cache.values()))
                status = AppointmentStatusEnum.NO_SHOW if row["status"] == "no_show" else AppointmentStatusEnum.COMPLETED
                db.add(Appointment(
                    patient_id=pid, department_id=dept.id, appointment_date=pd.to_datetime(row["appointment_date"]),
                    appointment_type=row["appointment_type"], status=status,
                ))
                batch += 1
                if batch % 2000 == 0:
                    db.commit()
            db.commit()
            print(f"   Inserted {len(appts_df)} appointments")

            events_path = os.path.join(RAW_DIR, "hospital_events.csv")
            if os.path.exists(events_path):
                events_df = pd.read_csv(events_path)
                for _, row in events_df.iterrows():
                    dept = dept_objs.get(row["department"])
                    db.add(HospitalEvent(
                        title=row["title"], event_date=pd.to_datetime(row["event_date"]),
                        department_id=dept.id if dept else None, severity=row["severity"],
                    ))
                db.commit()
                print(f"   Inserted {len(events_df)} hospital events")
        else:
            print(f"\nNo synthetic data found at {RAW_DIR}. Run: python -m scripts.generate_dataset")

        print("\nSeed complete. All patient/visit/appointment data is SYNTHETIC DEMO DATA.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
